### consumer-rest: echo application name
GET http://localhost:8085/nacos/discovery/consumer/rest/echo

### consumer-feign: echo application name
GET http://localhost:8086/nacos/discovery/consumer/feign/echo

