server:
  port: 8097
wx:
  miniapp:
    # 小程序配置(必填)
    appid: wx3b420e1a7df9acdc
    secret: 95587e9223db4b540de8943b8c85e063
    token:
    aesKey:
    msgDataFormat: JSON # 消息格式，XML或者JSON.
    # 存储配置redis(可选)
    config-storage:
      type: Memory
      key-prefix: wx:miniapp
#      redis:
#        host: 192.168.1.37
#        port: 6379
#        password: q4dkpDgTweEk3c0VJW3E
      # http客户端类型: HttpClient(默认), OkHttp, JoddHttp
      http-client-type: OkHttp