version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config:/etc/prometheus/
      - ./data:/prometheus
    ports:
      - "9090:9090"
    restart: always