spring:
  cloud:
    gateway:
      routes:
        - id: nacos-discovery-provider-route
          uri: lb://nacos-discovery-provider
          order: 1
          filters:
            - StripPrefix=1
            - RequestTime=true # 自定义局部过滤器 - 请求时间统计
            - name: BlacklistUrl # 自定义局部过滤器 - URL 黑名单过滤
              args:
                BlacklistUrl: /exception/**,/nacos/discovery/provider/exception/** # 多个参数使用 , 隔开
          predicates:
            - Path=/nacos-discovery-provider/**
