version: '3'
services:
  mysql:
    image: mysql:8
    restart: always
    hostname: mysql
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=V3Gezdrp1q3YD4mexFa1PzwN"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql
