server:
  port: 8087

jasypt:
  encryptor:
    password: XrDUx03bEMUfD5p0LMha97Kq

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/venus_example?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ENC(R51ZR8wEjCjHP71xWMCax/XMn2m4/R3tMJbAZVYUkTxYdVd2f6eDDrMZ0l0iAtfC)
    password: ENC(FdBYNWltUJOwXkH+Xo1H4RJHWW1x/FSZRFaHl5OqtujhgXthXpYDzMd2rofCQryVtQpGkqewcG0K5YmT6A6sMg==)
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: localhost
    port: 6379
    password: ENC(qC960sYbaeHUeJJfpgx+R+uqATuCDEC6EWM4OkZCTonpFmk/MTmbeB0L+DyFk0wAbroMs0Ryc9JlvVU3Rv7wjg==)
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 2000ms