version: "3.7"

services:
  grafana:
    image: grafana/grafana-enterprise:8.4.4
    container_name: grafana
    volumes:
      - ./data:/var/lib/grafana
      - ./logs:/var/log/grafana
    env_file:
      - ./config.monitoring
    ports:
      - "3000:3000"
    restart: always